### ISSUE TITLE
improvement: make a difference between references in "runtime code" & "test"

### ISSUE THREAD

**Issue by AugustinUpway** [gosvig123/reference_count_extension#10]
First of all, thanks for this awesome extension ! I always had something like that in mind, to always know if I'm dealing with a function used once or something used at many many different places.

## Improvement suggestion

Instead of showing the count of total references, it could be interesting to have two counts. One for "regular code" & one for "tests".

For example: I have a function called `createBike` with 13 references, but when I open VS code reference details, I can see that 12 of them are from test files (with the extension `.spec.ts` or `.test.ts`). So I'm dealing with a function used once but well tested !

Any thought on this ?

**Comment by gosvig123** [comment]
@AugustinUpway 
Thanks, happy you like it, i wasen't sure if anybody else was using it - but i find it somewhat useful in my day to day :)

the feedback makes sense, there is definitely still a lot to be desired, i think exclusion patterns is likely the easiest way to provide a lot of flexibility without getting super granular - but makes sense. 

I might look into adding some user configurable exclusion later this week, or if you are interested in contributing you are also most welcome. 

In terms of displaying multiple different counts, i also see what you mean - but for the time being i will likely just add the optionality to exclude based on file patterns.

**Comment by gosvig123** [comment]
@AugustinUpway 
Added in the exclusion option since it was really quick (should be available shortly if you update)

**Comment by AugustinUpway** [comment]
Hey, thanks for the quick change !
I've never developed VSCode extension so it's interesting ready the commit behind this !

I tried setting up a pattern to exclude my tests: `.(spec|test).ts` but unfortunately I see no change in the reference counter displayed. This regex looks right tho, no sure where is the issue 😢 
Any ideas ?

**Comment by gosvig123** [comment]
wups, yea i think I see the issue. Should probably have stopped coding that day😅
The query is fine, but i am applying it wrongfully.

Will update later
